"""Shared data types for the NPI engine.

These are intentionally minimal and source-agnostic: a Game doesn't know or
care whether it came from a scraped schedule CSV or was generated by a
simulation sampling a hypothetical result for a not-yet-played matchup. The
engine consumes lists of Game objects and nothing else.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Literal

Result = Literal["W", "L", "T"]
Site = Literal["home", "away", "neutral"]


@dataclass(frozen=True)
class Game:
    """
    One game, with all attributes from `team_id`'s perspective.
    """
    team_id: str
    opponent_id: str
    date: date
    result: Result
    site: Site = "neutral"
    overtime: bool = False
